### PR TITLE
Prac 06 feedback

### PR DESCRIPTION
**Pull request by MomoeYoshida**
Hi @zebdelrosario,
Could you check my codes for prac_06, please?
Thanks.
Momoe

### CODE REVIEW

**Review by zebdelrosario — COMMENTED** [review]
Try making commits in more spread-out steps; going from a blank file to a fully-complete program in a single commit seems unrealistic.

**Comment by zebdelrosario** [comment]
Good code, just some commit comments:

- Try making commit titles more specific; "Edit ..." doesn't offer a quick and easy overview of changes.
- Avoid making non-significant commits a regular thing; in some commits you have only edited single lines of docstring text; _(perhaps you can edit all the docstrings in a single commit?)_
- Try spreading out commits; some commits go from _**'empty program'**_ to _**'completed program'**_

**Review by zebdelrosario — COMMENTED** [review]
Try using similar-sounding variables for your guitar objects; instead of:_"guitar"_ and _"another"_ .
Try: _"guitar_one"_ and _"guitar_two"_

**Comment by MomoeYoshida** [comment]
> Try making commits in more spread-out steps; going from a blank file to a fully-complete program in a single commit seems unrealistic.

**Comment by MomoeYoshida** [comment]
> Try making commits in more spread-out steps; going from a blank file to a fully-complete program in a single commit seems unrealistic.

Thank you for your comment. Yeah, I'm struglling to make good commits... how many commits did you do for yours?

**Comment by MomoeYoshida** [comment]
> Good code, just some commit comments:
> 
> * Try making commit titles more specific; "Edit ..." doesn't offer a quick and easy overview of changes.
> * Avoid making non-significant commits a regular thing; in some commits you have only edited single lines of docstring text; _(perhaps you can edit all the docstrings in a single commit?)_
> * Try spreading out commits; some commits go from _**'empty program'**_ to _**'completed program'**_

Thank you very much for your greate advice. I would appreciate if you can tell me how you learned about such good commits techniques... haha.

**Pull request merged**
